name: Javascript Test Action
description: Testing Javascript Action

inputs:
  repo:
    description: GitHub repository name (user/repo)
    required: true

  script:
    description: Shell script to run
    required: true

runs:
  using: node12
  main: index.js
