name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug
      uses: ./
      with: { command: 'ls /' }

    - name: Debug
      uses: ./
      with: { command: 'touch hello.txt' }

    - name: Debug
      uses: ./
      with: { command: 'ls' }

